##########################
### CUSTOM KEYBINDINGS ###
##########################

# Bind Super + Shift + N to open nmtui in Kitty
bind = Super SHIFT, N, exec, kitty --title "Network Manager" nmtui
# Bind Super + SHIFT + V to togle copyq clipboard
bind = Super SHIFT, V, exec, copyq toggle
# bind Super + SHIFT + P to wlogout menu
bind = $mainMod SHIFT, P, exec, wlogout